services:
  # Databases
  userdb:
    container_name: userdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Phulam2003@
    restart: always
    ports:
      - "1401:1433"
    volumes:
      - sqlserver_user:/var/opt/mssql


  # Api gateway
  yarpapigateway:
    container_name: yarpapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    restart: on-failure:3
    ports:
      - "6006:8080"


  # Services
  eventservice.api:
    container_name: eventservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    restart: on-failure:3
    ports:
      - "6000:8080"


  gameservice.api:
    container_name: gameservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    restart: on-failure:3
    ports:
      - "6001:8080"


  mediaservice.api:
    container_name: mediaservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    restart: on-failure:3
    ports:
      - "6002:8080"


  notificationservice.api:
    container_name: notificationservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    restart: on-failure:3
    ports:
      - "6003:8080"


  paymentservice.api:
    container_name: paymentservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    restart: on-failure:3
    ports:
      - "6004:8080"


  userservice.api:
    container_name: userservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=userdb;Database=UserDb;User Id=sa;Password=Phulam2003@;Encrypt=False;TrustServerCertificate=True
      - Jwt__Issuer=VouSphere
      - Jwt__Audience=VouSphere
      - Jwt__SecretKey=bkdghy78ww2b-3nj9dfsnb-dfgdj-dfgdfg-dfgbdfgh232-3loqlwqe-3w25e2e4
    restart: on-failure:3
    depends_on:
      - userdb
    ports:
      - "6005:8080"


networks:
  default:
    name: vousphere_network