services:
  # Databases
  eventdb:
    container_name: eventdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=EventDb
    restart: always
    ports:
      - "5401:5432"
    volumes:
      - postgres_event:/var/lib/postgresql/data/


  voucherdb:
    container_name: voucherdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=VoucherDb
    restart: always
    ports:
      - "5402:5432"
    volumes:
      - postgres_voucher:/var/lib/postgresql/data/


  gamedb:
    container_name: gamedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=GameDb
    restart: always
    ports:
      - "5403:5432"
    volumes:
      - postgres_game:/var/lib/postgresql/data/


  mediadb:
    container_name: mediadb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=MediaDb
    restart: always
    ports:
      - "5404:5432"
    volumes:
      - postgres_media:/var/lib/postgresql/data/


  notificationdb:
    container_name: notificationdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=NotificationDb
    restart: always
    ports:
      - "5405:5432"
    volumes:
      - postgres_notification:/var/lib/postgresql/data/


  userdb:
    container_name: userdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Phulam2003@
    restart: always
    ports:
      - "1401:1433"
    volumes:
      - sqlserver_user:/var/opt/mssql


  # Message broker
  messagebroker:
    container_name: messagebroker
    hostname: vousphere-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" 


  # Api gateway
  yarpapigateway:
    container_name: yarpapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Jwt__Issuer=VouSphere
      - Jwt__Audience=VouSphere
      - Jwt__SecretKey=bkdghy78ww2b-3nj9dfsnb-dfgdj-dfgdfg-dfgbdfgh232-3loqlwqe-3w25e2e4
    restart: on-failure:3
    ports:
      - "6000:8080"


  # Services
  eventservice.api:
    container_name: eventservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=eventdb;Port=5432;Database=EventDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - MessageBroker__Host=amqp://vousphere-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    restart: on-failure:3
    depends_on:
      - eventdb
      - messagebroker
    ports:
      - "6001:8080"


  voucherservice.api:
    container_name: voucherservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=voucherdb;Port=5432;Database=VoucherDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - MessageBroker__Host=amqp://vousphere-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    restart: on-failure:3
    depends_on:
      - voucherdb
      - messagebroker
    ports:
      - "6002:8080"


  gameservice.api:
    container_name: gameservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=gamedb;Port=5432;Database=GameDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - MessageBroker__Host=amqp://vousphere-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    restart: on-failure:3
    depends_on:
      - gamedb
      - messagebroker
    ports:
      - "6003:8080"


  mediaservice.api:
    container_name: mediaservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=mediadb;Port=5432;Database=MediaDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - MessageBroker__Host=amqp://vousphere-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    restart: on-failure:3
    depends_on:
      - mediadb
      - messagebroker
    ports:
      - "6004:8080"


  notificationservice.api:
    container_name: notificationservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=notificationdb;Port=5432;Database=NotificationDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - MessageBroker__Host=amqp://vousphere-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    restart: on-failure:3
    depends_on:
      - notificationdb
      - messagebroker
    ports:
      - "6005:8080"


  paymentservice.api:
    container_name: paymentservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    restart: on-failure:3
    ports:
      - "6006:8080"


  userservice.api:
    container_name: userservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=userdb;Database=UserDb;User Id=sa;Password=Phulam2003@;Encrypt=False;TrustServerCertificate=True
      - Jwt__Issuer=VouSphere
      - Jwt__Audience=VouSphere
      - Jwt__SecretKey=bkdghy78ww2b-3nj9dfsnb-dfgdj-dfgdfg-dfgbdfgh232-3loqlwqe-3w25e2e4
      - MessageBroker__Host=amqp://vousphere-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    restart: on-failure:3
    depends_on:
      - userdb
      - messagebroker
    ports:
      - "6007:8080"


  emailservice.api:
    container_name: emailservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - SendgridEmailService__ApiKey=SG.9GFGZvnnT5-TK68EzANaQA.ZXxTKbSK3dxIxoImNjFY448IBXkv4vk0Z0UZ4KTkfdk
      - SendgridEmailService__SenderEmail=phulam.dev@gmail.com
      - SendgridEmailService__SenderName=Vousphere
      - MessageBroker__Host=amqp://vousphere-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    restart: on-failure:3
    depends_on:
      - messagebroker
    ports:
      - "6008:8080"


networks:
  default:
    name: vousphere_network

